version: '3'

services:
  
  api:
    platform: linux/amd64
    build: 
      context: .
    ports:
      - 9010:9010
    depends_on:
      - database
    volumes:
      - .:/app
  
  database:
    image: postgres:11.5-alpine
    volumes:
      - "db:/var/lib/postgresql/data"
      - ./:/app
    working_dir: /app
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  db: